apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: wireguard
spec:
  imageRepositoryRef:
    name: wireguard
  policy:
    filterTags:
      pattern: ^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>\d*)-(?P<buildmetadata>r\d*)-(?P<incr>ls\d*)
    semver:
      range: 1.0.*