---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: unifi 
spec:
  parentRefs:
    - name: traefik
      namespace: infrastructure 
      sectionName: passtrough-internal
  rules:
    - backendRefs:
        - name: unifi
          port: 8443
