apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: alert 
  namespace: monitoring
spec:
  summary: "watch all"
  eventMetadata:
    env: "development"
    cluster: "dev-cluster"
    region: ""
  providerRef:
    name: slack-bot
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: flux-system
    - kind: Kustomization
      name: '*'
      namespace: flux-system
    - kind: HelmRelease
      name: '*'
    - kind: HelmRepository
      name: '*'