apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack-bot
  namespace: monitoring
spec:
  type: slack
  channel: kubernetes
  address: https://slack.com/api/chat.postMessage
  secretRef:
    name: slack-bot-token