apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack-errors-provider
spec:
  type: slack
  channel: flux-system-errors
  address: https://slack.com/api/chat.postMessage
  secretRef:
    name: slack-bot-token