---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 15s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./monitoring
  prune: true
  wait: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      env: prod
