---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 10m
  chart:
    spec:
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: reflector
      interval: 10m

        
