# unifi-db deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-db
spec:
  selector:
    matchLabels:
      app: unifi-db
  template:
    metadata:
      labels:
        app: unifi-db
    spec:
      containers:
        - name: unifi-db
          image: docker.io/mongo:6.0.16-jammy # {"$imagepolicy": "apps:mongo-db"}
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - mountPath: /data/db
              name: fast-nfs
            - mountPath: /docker-entrypoint-initdb.d
              name: init
              readOnly: true
          envFrom:
            - secretRef:
                name: unifi-db-secret
          securityContext:
            runAsUser: 65534
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
      volumes:
        - name: fast-nfs
          persistentVolumeClaim:
            claimName: unifi-db
        - name: init
          secret:
            secretName: init-mongo-secret
