apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mongo-db
spec:
  imageRepositoryRef:
    name: mongo-db
  filterTags:
    pattern: '^(?P<semver>[0-9]*\.[0-9]*\.[0-9]*)-(?P<distro>[a-z]*)'
    extract: '$semver'
  policy:
    semver: 
      range: 6.x