apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 10m
  values:
    image:
      #repository: traefik # {"$imagepolicy": "flux-system:traefik:name"}
      repository: traefik
      #tag: 3.0.4 # {"$imagepolicy": "flux-system:traefik:tag"}
      tag: 3.1.0-rc3 
    providers:
      #kubernetesGateway: {}
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
    logs:
      level: DEBUG
      access:
        enabled: true
    experimental:
      plugins:
        bouncer:
          moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
          version: "v1.3.2"
      #kubernetesGateway:
      #  enabled: true
    additionalArguments:
      - --entryPoints.internal.address=:8443/tcp
      - --entryPoints.external.address=:8444/tcp
      - --entrypoints.web.http.middlewares=traefik-bouncer@kubernetescrd
      - --entrypoints.websecure.http.middlewares=traefik-bouncer@kubernetescrd
      - --entrypoints.internal.http.middlewares=traefik-bouncer@kubernetescrd
      - --entrypoints.external.http.middlewares=traefik-bouncer@kubernetescrd
      - --experimental.kubernetesgateway
      - --providers.kubernetesgateway
    service:
      spec:
        externalTrafficPolicy: Local
    ports:
      web:
        redirectTo:
          port: internal
      websecure:
        port: 8445
        expose:
          default: false
        exposedPort: 445
      internal:
        port: 8443
        expose:
          default: true
        exposed: true
        exposedPort: 443
      external:
        port: 8444
        expose:
          default: true
        exposedPort: 444
    volumes:
      - name: crowdsec-bouncer-tls
        mountPath: /etc/traefik/crowdsec-certs
        type: secret
