apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ldap
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ldap
    namespace: flux-system
  policy:
    semver: 
      range: 2.6.x