kind: Service
apiVersion: v1
metadata:
  name: ldap 
  namespace: ldap
spec:
  selector:
    app: ldap
  ports:
    - port: 636
      name: ldaps
      targetPort: ldaps
    - port: 389
      name: ldap
      targetPort: ldap