apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - target: 
      kind: Kustomization
      name:  flux-system
    patch: |
      - op: add
        path: /spec/decryption/provider
        value: sops
      - op: add
        path /spec/decryption/secretRef/name
        value: sops-age