apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: prowlarr
spec:
  imageRepositoryRef:
    name: prowlarr
  filterTags:
    pattern: '^(?P<semver>1\.[0-9]*\.[0-9]*)\.(?P<meta>[0-9]*-ls)(?P<tag>[0-9]*)'
    extract: '$tag'
  policy:
    numerical: 
      order: asc