apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: cert-manager
stringData:
    token: ENC[AES256_GCM,data:jh9eR1WLLn67RcfDGpqop3jvWFRuRnZbb5Iry7LUyma1cb8ILNjEyw==,iv:4Yq/V0sV87AJt1cxOrzYG/ykVRBQSF7NhTJprhftIe0=,tag:9gaDSh/pthO0RiCxwt4O+g==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12th6l9858s0vvr9vwgvj3h3fr02taeq5xx64s0p4uvsra9vstqrqseqv3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZldic3pFWWhlL0tkU2ZN
            UW5vc0lxeThOeFdwcWMvUUVlWWozMFhPczFFCmkrblNvRDNmZzhsbjlhazBtQkZT
            MkFxbThtdDZ4ZnJsS3B5OXFSUHpIMk0KLS0tIDd3MEJsSThZYlYyRWszbDFuemlk
            VWRLOWdmRkVWWW90c3lISlZNUEtzbnMKvY0iox8SZFmRT84zfH8tyf2NUlYBPcvC
            /0G3VlXJh7Dp96F01HHOaHpV2TQ3qOeV1aW/Vh+arRULPezvmFks2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T11:17:50Z"
    mac: ENC[AES256_GCM,data:8ImlRMKElmmDicMkm4D0e6d/fKSs7lrl17tNF9YOGBEnv8WiMvgG7i0rE97Vf1CwfI/WdhRMrec91nzoMT62pt7lTFKcv+JzoNVpslXWGTauvGi1v0KvGVOvnBUamotoUzOrJVzxi/ZWIlVUBO9lY1AeqlPiunLy4ZMPlwkSpnU=,iv:vStqM0orGEmkLLuHINWSXQy8olEvgKnomfdu5z5EviM=,tag:WQsV4xXfcWb7+uIfq+lFTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
