namespace: infrastructure
resources:
  - ../base
patches:
  - target:
      kind: Gateway
      name: traefik
    patch: |
      - op: replace  
        path: /spec/listeners/0/hostname
        value: "*.dev.${domain}"
      - op: add
        path: /spec/listeners/0/tls
        value:
          certificateRefs:
            - name: "dev.${domain}"
  - target:
      kind: IPAddressPool
      name: pool
    patch: |
      - op: replace
        path: /spec/addresses
        value:
          - 10.0.111.40/29