---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 10m
  values:
    experimental:
      kubernetesGateway:
        enabled: true
    additionalArguments:
      - --entryPoints.internal.address=:8443/tcp
      - --entryPoints.external.address=:8444/tcp
    service:
      spec:
        loadBalancerIP: 10.0.111.40
    ports:
      web:
        redirectTo:
          port: internal
      websecure:
        expose:
          default: false
        exposedPort: 445
      internal:
        port: 8443
        expose:
          default: true
        exposed: true
        exposedPort: 443
      external:
        port: 8444
        expose:
          default: true
        exposedPort: 444