---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 10m
  values:
      image:
        repository: traefik
        tag: 3.0.1
      additionalArguments:
        - --log.level=INFO
        - --entryPoints.internal.address=:443/tcp
        - --entryPoints.external.address=:444/tcp
      ports:
        web:
          port: 80
          redirectTo:
            port: internal
        websecure:
          expose:
            default: false
          exposedPort: 445
        internal:
          port: 443
          expose:
            default: true
          exposed: true
          exposedPort: 443
        external:
          port: 444
          expose:
            default: true
          exposedPort: 444
      providers:
        kubernetesCRD:
          allowCrossNamespace: true
          allowExternalNameServices: true
      #service:
      #  spec:
      #    loadBalancerIP: 10.0.111.40