---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fast-nfs
  namespace: nfs-provisioner
spec:
  interval: 10m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
      interval: 10m
  values:
    storageClass:
      name: fast-nfs
      provisionerName: fast-nfs
      onDelete: retain
      pathPattern: ${.PVC.name}
