---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crowdsec
  namespace: flux-system
spec:
  dependsOn:
    - name: reflector 
  interval: 1h
  retryInterval: 15s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/crowdsec
  prune: true
  wait: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age