---
# Misc
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-miscellaneous
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/miscellaneous/dev
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# Metallb controller
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-controller
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/metallb/controller
  prune: true
  wait: true
---
# Metallb config
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-controller
  interval: 1h
  retryInterval: 15s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/metallb/config
  prune: true
  wait: true
  patches:
  - target:
      kind: IPAddressPool
      name: pool
    patch: |
      - op: replace
        path: /spec/addresses
        value:
          - 10.0.111.40/29
---
# Controllers
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-config 
  interval: 1h
  retryInterval: 15s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret 
        name: cluster-secrets
---
# Configs
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 15s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret 
        name: cluster-secrets
  patches:
    - target:
        kind: Gateway
      patch: |
        - op: replace  
          path: /spec/listeners/0/hostname
          value: "*.dev.${domain}"
        - op: add
          path: /spec/listeners/0/tls
          value:
            certificateRefs:
              - name: "dev.${domain}"
        - op: replace
          path: /spec/listeners/1/hostname
          value: "*.${domain}"
---
# Monitoring
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-monitoring
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/monitoring
  prune: true
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/eventMetadata/env
          value: dev
        - op: replace
          path: /spec/eventMetadata/cluster
          value: dev-cluster
      target:
        kind: Alert
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# crowdsec
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-crowdsec
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/crowdsec
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age




