# Metallb controller
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-controller
  namespace: flux-system
spec:
  suspend: true
  interval: 1h
  retryInterval: 15s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/metallb/controller
  prune: true
  wait: true

---
# Metallb config
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  suspend: false
  dependsOn:
    - name: metallb-controller
  interval: 1h
  retryInterval: 15s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/metallb/config
  prune: true
  wait: true
  patches:
  - target:
      kind: IPAddressPool
      name: pool
    patch: |
      - op: replace
        path: /spec/addresses
        value:
          - 10.0.111.40/29
---