# Metallb controller
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 15s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/nfs-provisioner
  prune: true
  wait: false
  patches:
    - target:
        kind: HelmRelease
      patch: |
        - op: add
          path: /spec/values
          value:
            nfs:
              server: 10.0.111.20
              path: /nfs/containers