# Metallb controller
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  suspend: false
  interval: 1h
  retryInterval: 15s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/nfs-provisioner
  prune: true
  wait: false
  patches:
    - target:
        kind: HelmRelease
        name: fast-nfs
      patch: |
        - op: add
          path: /spec/values/nfs
          value:
            server: 192.168.12.20
            path: /nfs/containers