---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets-kustomization
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1m
  path: ./clusters/dev-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-secrets
