apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-controller
  namespace: flux-system
spec:
  suspend: true
  dependsOn:
    - name: metallb-config 
    - name: reflector
    - name: cert-manager-controller
  interval: 1h
  retryInterval: 15s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/traefik/controller
  prune: true
  wait: true
  patches:
    - target:
        kind: HelmRelease
      patch: |
        - op: add
          path: /spec/values/service/spec/loadBalancerIP
          value: 10.0.111.40
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-config
  namespace: flux-system
spec:
  suspend: true
  dependsOn:
    - name: traefik-controller 
  interval: 1h
  retryInterval: 15s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/traefik/config
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret 
        name: cluster-secrets
  patches:
    - target:
        kind: Gateway
      patch: |
        - op: replace  
          path: /spec/listeners/0/hostname
          value: "*.dev.${domain}"
        - op: add
          path: /spec/listeners/0/tls
          value:
            certificateRefs:
              - name: "dev.${domain}"
