---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-config 
  interval: 1h
  retryInterval: 15s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/vaultwarden
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret 
        name: cluster-secrets
  patches:
    - target:
        kind: HTTPRoute
        name: vaultwarden
      patch: |
        - op: add
          path: /spec/hostnames
          value:
            - "vaultwarden.${domain}" 
            - "vaultwarden.dev.${domain}" 