---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: gluetun
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: gluetun
    namespace: flux-system
  filterTags:
    pattern: '^v(?P<semver>3\.[0-9]*\.[0-9]*)'
    extract: '$semver'
  policy:
    semver: 
      range: 3.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: qbittorrent
    namespace: flux-system
  filterTags:
    pattern: ^(?P<semver>4\.[0-9]*\.[0-9]*)(?P<meta>-r[0-9]]*)-ls(?P<tag>[0-9]*)
    extract: '$tag'
  policy:
    numerical: 
      order: asc