---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |-
    .:53 {
        errors
        health
        rewrite stop {
          name regex (.*)-ns-(.*)\.${domain_name}\.${domain_country}\.$ {1}.{2}.svc.cluster.local.
          answer name (.*)\.(.*)\.svc\.cluster\.local {1}-ns-{2}.${domain_name}.${domain_country}.
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          ttl 30
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
