---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: contour
spec:
  interval: 10m
  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 10m
  values:
    contour: 
      image:
        repository: bitnami/contour
        tag: 1.29.1-debian-12-r0
    envoy:
      image:
        repository: bitnami/envoy
        tag: 1.29.5-debian-12-r0