apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: default
stringData:
    CF_DOMAIN: ENC[AES256_GCM,data:DfWgXhbAFP2Ftv8=,iv:xji1KljAnPRTh9WMqTOq2gyYR9l481wnB5OOhv+Ictc=,tag:F35ij+1gPCNIhMpOb7WIpg==,type:str]
    CF_EMAIL: ENC[AES256_GCM,data:5LVoEey0XoeWmfXSDMmQMlVYp48=,iv:DWHpt/FS8Jd03w3E73hY6W2JSjn0dGBjVuqPi9VO6rI=,tag:/Q4AtmsS251pw/Oum/xahg==,type:str]
    CF_TOKEN: ENC[AES256_GCM,data:6rwJPI5VS6x6S0+bCNiWTKyXe2Ma5pc/zdSDjAwik1zL5B9Brt5DQw==,iv:FK5PI9M26LtW/ITvCRP+7Wz7QC28UWoW54H1z11heJI=,tag:frhnFkxCtYgtys6Sg23/7g==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12th6l9858s0vvr9vwgvj3h3fr02taeq5xx64s0p4uvsra9vstqrqseqv3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeTZlZWkrL0lBQWVJb3pL
            MGsvcUlTSTlQOEJoZmw0b1E1NkJzQldXK1QwCnp3cC96MURjbHExT0tic1drRWY3
            SG1uSWhzcTA5aE5VaStPYXdlKzFUSjQKLS0tIEEwcVZiZEN1U2dFL1grRkZka0Jx
            ZGl4alh2NUJKSHNuZ0RzK09UWkFrNU0KAkxZ5/uyyBdE3chZQmgMF2e38kVbLf9c
            U6vsIviB6BDLpuL4j1cp1CweUoD3rc2jmmU6cX6uChaPr7R8bEt1yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T14:57:45Z"
    mac: ENC[AES256_GCM,data:/hryDh9yNdEr5Ax3mgnmbxObhoy4xzeCHqgEl/H2D90bHyRj2VcUAQcw+8HKN7fBup7Bs+CicasZFnVMRobcQ4cNIcdqZhS3Wl/buR1SNGf59UgE4PpS4WL5lFEmNHLWehpr0u/0qRUj09sP8Mw3cy4ibI0pmSX/+YuNjJFTxDg=,iv:/SMJIpP/ZRliCfypoKwn2281+dWYVFGc4PBFU5tOiEY=,tag:tSrnXwoB3TcRxj+oxNtSeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
