apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 10m
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 10m
  values:
    controller:
      image:
        repository: quay.io/metallb/controller # {"$imagepolicy": "flux-system:metallb-controller:name"}
        tag: v0.14.5 # {"$imagepolicy": "flux-system:metallb-controller:tag"}
    speaker:
      frr:
        enabled: false
      image:
        repository: quay.io/metallb/speaker # {"$imagepolicy": "flux-system:metallb-speaker:name"}
        tag: v0.14.5 # {"$imagepolicy": "flux-system:metallb-speaker:tag"}
