apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: metallb-controller
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: metallb-controller
    namespace: flux-system
  policy:
    semver: 
      range: v0.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: metallb-speaker
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: metallb-speaker
    namespace: flux-system
  policy:
    semver: 
      range: v0.x
