# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: wireguard
spec:
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - name: wireguard
          image: lscr.io/linuxserver/wireguard:1.0.20210914-r4-ls51 # {"$imagepolicy": "flux-system:wireguard"}
          ports:
            - containerPort: 51820
              protocol: UDP
              name: wireguard
          volumeMounts:
            - mountPath: /config
              name: fast-nfs
          envFrom:
            - configMapRef:
                name: common-env
            - configMapRef:
                name: wireguard-env
          securityContext:
            capabilities:
              add: [NET_ADMIN]
            sysctls:
              - name: net.ipv4.conf.all.src_valid_mark
                value: '1'
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
      volumes:
        - name: fast-nfs
          persistentVolumeClaim:
            claimName: wireguard
