---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
spec:
  ports:
    - port: 51820
      protocol: UDP
      targetPort: wireguard
  selector:
    app: wireguard
  type: LoadBalancer

