apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: bouncer
    namespace: infrastructure
spec:
    plugin:
        bouncer:
            enabled: true
            crowdsecMode: stream
            crowdsecLapiScheme: https
            crowdsecLapiHost: crowdsec-service.infrastructure:8080
            # crowdsecLapiKey: nGhnkR5jPxNf2gRNbJGxSMpCxmuJHi4PWA2h
            crowdsecLapiTLSCertificateAuthorityFile: /etc/traefik/crowdsec-certs/ca.crt
            crowdsecLapiTLSCertificateBouncerFile: /etc/traefik/crowdsec-certs/tls.crt
            crowdsecLapiTLSCertificateBouncerKeyFile: /etc/traefik/crowdsec-certs/tls.key
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12th6l9858s0vvr9vwgvj3h3fr02taeq5xx64s0p4uvsra9vstqrqseqv3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2K2d0MFV6WW10djdVWlhi
            czJPbm9pcmdpMXc3Z0daZW0yZXozTDIrcVJjCkdVTzBjcDNnZEZXUGZXNjVLQytQ
            dWJIK0JjSk5ldGJPeXdENmdNUGVocFUKLS0tIGtNd3RKR1FWeENNVHR0MEp0TjJm
            K29SS2Y2a2RJREU4ZkFuWHdJN096bFUK/Y4awvsALw+7OyEQZvKDyCl3Baif5dPC
            ZaVFIPdMRpUkYZxzRuWDdbUJEajYfd9r7Aqq5bqHyM2WvOzKNxYVEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T13:33:05Z"
    mac: ENC[AES256_GCM,data:JkxAtO09W/+YEHyWGiQbx/F06LRxQYbCh+kEno4jExMh6OnnhIX67yCljMFHXtio1cN3X6X+0ZZuqgwohauN83EWMnhZnyCujemPao3WaJwjiMKnvOLNLmMc7cdwdKNzUKoYYAmIDqI0TvktX/cZAWWgHnFsVPmy1Kywb7FhFLM=,iv:Scg9V/mxDiR/k///CT5IfCggily/FWXulSv/Hcu+Bb0=,tag:7EqaHyyCZCjThwvhRp8ZQw==,type:str]
    pgp: []
    encrypted_regex: ^crowdsecLapiKey$
    version: 3.8.1
