apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: bouncer
    namespace: infrastructure
spec:
    plugin:
        bouncer:
            enabled: true
            crowdsecMode: stream
            crowdsecLapiScheme: https
            crowdsecLapiHost: crowdsec-service.crowdsec:8080
            crowdsecLapiKey: ENC[AES256_GCM,data:s+H5MStwb3f7NtJj8Yk2lFmddqYhJJUWnSPFEQB0Snpy/0eoToZSgw==,iv:KwrMz3PmFVauKbfVTBy3S35Cq37fSRoPIh+LNl1OXqg=,tag:PDbd3LvcT+ZiUHIw/GVkIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12th6l9858s0vvr9vwgvj3h3fr02taeq5xx64s0p4uvsra9vstqrqseqv3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2K2d0MFV6WW10djdVWlhi
            czJPbm9pcmdpMXc3Z0daZW0yZXozTDIrcVJjCkdVTzBjcDNnZEZXUGZXNjVLQytQ
            dWJIK0JjSk5ldGJPeXdENmdNUGVocFUKLS0tIGtNd3RKR1FWeENNVHR0MEp0TjJm
            K29SS2Y2a2RJREU4ZkFuWHdJN096bFUK/Y4awvsALw+7OyEQZvKDyCl3Baif5dPC
            ZaVFIPdMRpUkYZxzRuWDdbUJEajYfd9r7Aqq5bqHyM2WvOzKNxYVEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T06:18:34Z"
    mac: ENC[AES256_GCM,data:zRjYvJsOgMHfn2o0jDMdQPDpjs71U3EIbixHqId2jp7RuTy3m3QQOto1wjjGrcsrdJ6GnrOsHANtuadHXWZPcGGf+5R4vDMr682al0+PiuXRFLqOtaKmpfgk8FXMg6W837ghrZEfRp2DSy0e5GDBQJQu0nT1N0GsxdG0kh6MPAg=,iv:qaVNo0MzErUFRhuYd29iRH63kjeORKotLUDzDrN3+iI=,tag:aVrVgmQ2FAYoWSOowdjeqQ==,type:str]
    pgp: []
    encrypted_regex: ^crowdsecLapiKey$
    version: 3.8.1
