apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: bouncer
    namespace: infrastructure
spec:
    plugin:
        bouncer:
            enabled: true
            crowdsecMode: stream
            crowdsecLapiScheme: https
            crowdsecLapiHost: crowdsec-service.crowdsec:8080
            crowdsecLapiKey: ENC[AES256_GCM,data:X7JfE+VFjyjraJyRxETjkb9BvEWU9cKB4yDVZPA+gM48qYFh,iv:Bq5ZbB87tcGJQayh35FSOcmPkmbYSbNIztc6ROZm8Tk=,tag:ujCn4HEP77woEwFkkGCMzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12th6l9858s0vvr9vwgvj3h3fr02taeq5xx64s0p4uvsra9vstqrqseqv3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2K2d0MFV6WW10djdVWlhi
            czJPbm9pcmdpMXc3Z0daZW0yZXozTDIrcVJjCkdVTzBjcDNnZEZXUGZXNjVLQytQ
            dWJIK0JjSk5ldGJPeXdENmdNUGVocFUKLS0tIGtNd3RKR1FWeENNVHR0MEp0TjJm
            K29SS2Y2a2RJREU4ZkFuWHdJN096bFUK/Y4awvsALw+7OyEQZvKDyCl3Baif5dPC
            ZaVFIPdMRpUkYZxzRuWDdbUJEajYfd9r7Aqq5bqHyM2WvOzKNxYVEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T06:47:49Z"
    mac: ENC[AES256_GCM,data:mwhGrWLDecErIN5MPURs58CSWhDz7aabLpPGuS5LfN/btSa21v9F5nNIRraY2x/dg5gGKpIUVZ7j/ZSxsHe9KMe7+Euiu5+78PqWUsb2swLiSUM3Z4A9MRogVMAmXeNPqLuCTzTuiTLMgRpfQwt+7LSuPiK5TsyWAZe9/CbXLJ4=,iv:fJozXoJK1pKoVGvUlJtYPA6c1TexbPcYtrdDcJsDv4Q=,tag:mmaLc/cMrsqYugW+rn0XRg==,type:str]
    pgp: []
    encrypted_regex: ^crowdsecLapiKey$
    version: 3.8.1
