apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: bouncer
    namespace: infrastructure
spec:
    plugin:
        bouncer:
            enabled: true
            crowdsecMode: stream
            crowdsecLapiScheme: https
            crowdsecLapiHost: crowdsec-service.crowdsec:8080
            crowdsecLapiKey: ENC[AES256_GCM,data:IjUFzE7ChWkgMDb7EdJahHrRetR8d1btVVjq3PutAANSzOvW,iv:Z3ykPuKQVAg+xJ6ZGs2jD00/fNVNbscMqezactWvrV8=,tag:uGZP2a02xPIPRw0MwTm57g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12th6l9858s0vvr9vwgvj3h3fr02taeq5xx64s0p4uvsra9vstqrqseqv3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2K2d0MFV6WW10djdVWlhi
            czJPbm9pcmdpMXc3Z0daZW0yZXozTDIrcVJjCkdVTzBjcDNnZEZXUGZXNjVLQytQ
            dWJIK0JjSk5ldGJPeXdENmdNUGVocFUKLS0tIGtNd3RKR1FWeENNVHR0MEp0TjJm
            K29SS2Y2a2RJREU4ZkFuWHdJN096bFUK/Y4awvsALw+7OyEQZvKDyCl3Baif5dPC
            ZaVFIPdMRpUkYZxzRuWDdbUJEajYfd9r7Aqq5bqHyM2WvOzKNxYVEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T22:10:39Z"
    mac: ENC[AES256_GCM,data:Y2ac6t/wXJAK/F9iD532PN3hG4RfztUq1BFno0yS/41JSqM+AzVZyjP1rllkfl13DEegrfDMGP5EaKelJW1SxRBHPhAqDeQvrNEWu0awvRnkArmxhipa2Z9/slecBzgMNSieCeKSY+hUdG9eYL/L/sRrTVkcjLciYlmYziE9UA0=,iv:w8qQofnVHcFhXIY8iI6g+xhukvZeoy5Gdky6BLDGBwc=,tag:qCBWnOm9AIWFWjxutafzWg==,type:str]
    pgp: []
    encrypted_regex: ^crowdsecLapiKey$
    version: 3.8.1
