apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: radarr
spec:
  imageRepositoryRef:
    name: radarr
  filterTags:
    pattern: '^(?P<semver>5\.[0-9]*\.[0-9]*)\.(?P<meta>[0-9]*-ls)(?P<tag>[0-9]*)'
    extract: '$tag'
  policy:
    numerical: 
      order: asc