resources:
  - ../base
patches:
  # prowlarr
  - target:
      kind: HTTPRoute
      name: prowlarr
    patch: |
      - op: add
        path: /spec/hostnames
        value:
          - "prowlarr.${env}.${domain}"
  # radarr
  - target:
      kind: HTTPRoute
      name: radarr
    patch: |
      - op: add
        path: /spec/hostnames
        value:
          - "radarr.${env}.${domain}"
  # sonarr
  - target:
      kind: HTTPRoute
      name: sonarr
    patch: |
      - op: add
        path: /spec/hostnames
        value:
          - "sonarr.${env}.${domain}"
  # torrent
  - target:
      kind: HTTPRoute
      name: torrent
    patch: |
      - op: add
        path: /spec/hostnames
        value:
          - "torrent.${env}.${domain}"