namespace: apps
resources:
  - ../base
patches:
  - path: patch_wg_service.yml
  # vaultwarden
  - target:
      kind: HTTPRoute
      name: vaultwarden
    patch: |
      - op: add
        path: /spec/hostnames
        value:
          - "vaultwarden.${domain}" 
          - "vaultwarden.dev.${domain}" 
  # prowlarr
  - target:
      kind: HTTPRoute
      name: prowlarr
    patch: |
      - op: add
        path: /spec/hostnames
        value:
          - "prowlarr.dev.${domain}"
  # radarr
  - target:
      kind: HTTPRoute
      name: radarr
    patch: |
      - op: add
        path: /spec/hostnames
        value:
          - "radarr.dev.${domain}"