namespace: apps
resources:
  - ../base
patches:
  - path: patch_wg_service.yml
  - target:
      kind: HTTPRoute
      name: vaultwarden
    patch: |
      - op: add
        path: /spec/hostnames
        value:
          - "vaultwarden.${domain}" 
          - "vaultwarden.dev.${domain}" 
  - target:
      kind: HTTPRoute
      name: prowlarr
    patch: |
      - op: add
        path: /spec/hostnames
        value:
          - "prowlarr.dev.${domain}"