apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: image-automations-alert
spec:
  summary: "Image automations notifications"
  eventMetadata:
    env: "${env}"
    cluster: "${env}-cluster"
  providerRef:
    name: image-automations-provider
  eventSeverity: info
  eventSources:
    # image-automation
    - kind: ImageUpdateAutomation
      name: "*"
      namespace: flux-system

    
