---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: slow-nfs
spec:
  interval: 10m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
      interval: 10m
  valuesFrom:
  - kind: Secret
    name: slow-nfs-values
  values:
    storageClass:
      name: slow-nfs
      provisionerName: slow-nfs
      onDelete: retain
      pathPattern: medias
