---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${email}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector:
          dnsNames: 
          - "*.${domain}"
          - "*.dev.${domain}"
          - "*.prod.${domain}"
        dns01:
          cloudflare:
            email: ${email}
            apiTokenSecretRef:
              name: cloudflare-token
              key: token
