---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: gluetun 
spec:
  image: qmcgaw/gluetun
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: qbittorrent
spec:
  image: lscr.io/linuxserver/qbittorrent
  interval: 24h