---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: gluetun
spec:
  imageRepositoryRef:
    name: gluetun
  filterTags:
    pattern: '^v(?P<semver>3\.[0-9]*\.[0-9]*)'
    extract: '$semver'
  policy:
    semver: 
      range: 3.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: qbittorrent
spec:
  imageRepositoryRef:
    name: qbittorrent
  filterTags:
    pattern: ^(?P<semver>4\.[0-9]*\.[0-9]*)(?P<meta>-r[0-9]]*)-ls(?P<tag>[0-9]*)
    extract: '$tag'
  exclusionList:
  - "v3.38.0"
  - "3.38.0"
  policy:
    numerical: 
      order: asc