apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-env
  namespace: crowdsec
data:
  DISABLE_LOCAL_API: "false"
  DISABLE_ONLINE_API: "false"
  PARSERS: "crowdsecurity/cri-logs crowdsecurity/whitelists"
  COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik Dominic-Wagner/vaultwarden crowdsecurity/unifi"
  DISABLE_PARSERS: "crowdsecurity/whitelists"