---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
spec:
  interval: 10m
  chart:
    spec:
      chart: crowdsec
      sourceRef:
        kind: HelmRepository
        name: crowdsec
      interval: 10m
  values:
    container_runtime: containerd
    tls:
      enabled: true
    agent:
      acquisition:
        - namespace: infrastructure
          podName: traefik-*
          program: traefik
      env:
        - name: PARSERS
          value: "crowdsecurity/cri-logs crowdsecurity/whitelists"
        - name: COLLECTIONS
          value: "crowdsecurity/linux crowdsecurity/traefik Dominic-Wagner/vaultwarden crowdsecurity/unifi"
      persistentVolume:
        config:
          enabled: false
    lapi:
      dashboard:
        enabled: false
        ingress: 
          host: dashboard.local
          enabled: true
      persistentVolume:
        config:
          enabled: false
        data:
          enabled: false
      resources:
        requests:
          cpu: 250m
          memory: 200Mi
        limits:
          memory: 200Mi
      env:
        - name: DISABLE_LOCAL_API
          value: "false"
        - name: DISABLE_ONLINE_API
          value: "false"
      envFrom:
        - secretRef:
            name: crowdsec


        
