---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  interval: 10m
  chart:
    spec:
      chart: crowdsec
      sourceRef:
        kind: HelmRepository
        name: crowdsec
      interval: 10m
  values:
    container_runtime: containerd
    tls:
      enabled: true
      bouncer:
        reflector:
          namespaces: ["traefik"]
    agent:
      acquisition:
        - namespace: infrastructure
          podName: traefik-*
          program: traefik
        - namespace: apps
          podName: vaultwarden-*
          program: vaultwarden
        - namespace: apps
          podName: unifi-*
          program: unifi
      envFrom:
        - configMapRef:
            name: crowdsec-env
      persistentVolume:
        config:
          enabled: false
    lapi:
      dashboard:
        enabled: false
        ingress: 
          host: dashboard.local
          enabled: true
      persistentVolume:
        config:
          enabled: false
        data:
          enabled: false
      resources:
        requests:
          cpu: 250m
          memory: 200Mi
        limits:
          memory: 200Mi
      envFrom:
        - secretRef:
            name: crowdsec
        - configMapRef:
            name: crowdsec-env


        
