---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  interval: 10m
  chart:
    spec:
      chart: crowdsec
      sourceRef:
        kind: HelmRepository
        name: crowdsec
      interval: 10m
  valuesFrom:
    - kind: Secret
      name: slack-values
  values:
    config:
      profiles.yaml: |
        name: default_ip_remediation
        filters:
          - Alert.Remediation == true && Alert.GetScope() == "Ip"
        decisions:
          - type: ban
            duration: 4h
        notifications:
          - slack_default
    container_runtime: containerd
    tls:
      enabled: true
      bouncer:
        reflector:
          namespaces: ["traefik"]
    agent:
      acquisition:
        - namespace: infrastructure
          podName: traefik-*
          program: traefik
        - namespace: apps
          podName: vaultwarden-*
          program: vaultwarden
        - namespace: apps
          podName: unifi-*
          program: unifi
      env:
        - name: DISABLE_LOCAL_API
          value: "false"
        - name: DISABLE_ONLINE_API
          value: "false"
        - name: PARSERS
          value: "crowdsecurity/cri-logs crowdsecurity/whitelists"
        - name: COLLECTIONS
          value: "crowdsecurity/linux crowdsecurity/traefik Dominic-Wagner/vaultwarden crowdsecurity/unifi"
        - name: DISABLE_PARSERS
          value: "crowdsecurity/whitelists"
      persistentVolume:
        config:
          enabled: false
    lapi:
      dashboard:
        enabled: false
        ingress: 
          host: dashboard.local
          enabled: true
      persistentVolume:
        config:
          enabled: false
        data:
          enabled: false
      resources:
        requests:
          cpu: 250m
          memory: 200Mi
        limits:
          memory: 200Mi
      envFrom:
        - secretRef:
            name: crowdsec
        - configMapRef:
            name: crowdsec-env


        
