apiVersion: v1
kind: Secret
metadata:
    name: crowdsec
type: Opaque
stringData:
    DISABLE_ONLINE_API: ENC[AES256_GCM,data:JJy4iSY=,iv:xQc/dJNSaOBWm0Vkqvt/+G2EJSlHk5oH4Foag7Y33lU=,tag:g1b+TOPIPibCpI28pcXYJw==,type:str]
    ENROLL_KEY: ENC[AES256_GCM,data:u+cbi6RQtKW9Xp8VvLa1ys7js218lOWYUik+pvk4/j9mqtIuJNs9sw==,iv:synuWDoMvhBuiXucZLp1tVxBsbMD5PS490Hwv03zQeY=,tag:YEJ8076H+om+gXSeaTohSw==,type:str]
    ENROLL_INSTANCE_NAME: ENC[AES256_GCM,data:ShsA,iv:J880mRXdDgJVAtrGI8LXMuWOX0Sx+i252PJODMa35hI=,tag:4XIE3SB00w3CTmLombAxAQ==,type:str]
    ENROLL_TAGS: ENC[AES256_GCM,data:Xehf5d+mL/g/WbRU,iv:pCyivYPWvkTCYjF3U0gq7/yT+qOM6CdDpI8ZKstT/fg=,tag:sxDRVoc8bSUMEC+YHFBgpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12th6l9858s0vvr9vwgvj3h3fr02taeq5xx64s0p4uvsra9vstqrqseqv3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bTRsd1hhTEUyVis1Q3FF
            ZmJUc3NvRnAxQ3lKQXlZWGZnK0xVc3Y1VUdjClJsUlJLeE9OSWxiSHliTHBML0hr
            Vnd5NWk1YW5hNWR2U2U3c2hVelh2eTQKLS0tIDhvdkVQakZrdFp4UVhVbVBCeEEx
            djNVNnB5aG1WU1BlTkl6TlNaSngyaVEKGWsY27QuFU1U8tLgse4EOB+j3GDYlRhv
            OIgcgx0fRTh7GI1/LNjFX3k8OIT1TLZWzhwtO/Rj7ri72QoqHEqpPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T06:17:43Z"
    mac: ENC[AES256_GCM,data:8eexz/kEUe4RgVmsyMC326UuXdXwikkxJ01LckeAHzNE97712cw4nuoyVFvpGRU49md5PmZLdpueoupKNHYmUJEKWdcE3iH8u9zNQSSSJM2KZ8usDtVTDv4JTtWiCaJfB47+tv+Edfa1NA21QsXl3Py45L+FmwZEvQxAP5sF7yE=,iv:IMrmCTgqZzc2Sk36x80PNPGo32rlpki5CDvrkM5dHZk=,tag:vwAWiDi137HMcVMrt4fzQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
