apiVersion: v1
kind: Secret
metadata:
    name: crowdsec
type: Opaque
stringData:
    DISABLE_ONLINE_API: ENC[AES256_GCM,data:3RrBxZM=,iv:l9oC+cKmEKSoBFeihlG9C4TSXEcDdpZL8sQ/7WcC3d4=,tag:DMUS04f5UJJslNoTRV0ftw==,type:str]
    DISABLE_LOCAL_API: ENC[AES256_GCM,data:wqcdjEM=,iv:7646YkM9y1cmY0LGSAoR9sh4i06ohAnNHm4nGKFhpMU=,tag:plkLO3GZxP0KqkrNmmVNWw==,type:str]
    ENROLL_KEY: ENC[AES256_GCM,data:Rids2ApfaIJRWOClxrgOWyWfY9pUgGfKRA==,iv:qfkvTSXEEDq6JH1LoWm3Zn+mKww/81BPcMXAgYjIU6I=,tag:qxk1swGOCGAtT694UMLJAA==,type:str]
    ENROLL_INSTANCE_NAME: ENC[AES256_GCM,data:ShsA,iv:J880mRXdDgJVAtrGI8LXMuWOX0Sx+i252PJODMa35hI=,tag:4XIE3SB00w3CTmLombAxAQ==,type:str]
    ENROLL_TAGS: ENC[AES256_GCM,data:Xehf5d+mL/g/WbRU,iv:pCyivYPWvkTCYjF3U0gq7/yT+qOM6CdDpI8ZKstT/fg=,tag:sxDRVoc8bSUMEC+YHFBgpg==,type:str]
# BOUNCER_KEY_traefik: nGhnkR5jPxNf2gRNbJGxSMpCxmuJHi4PWA2h
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12th6l9858s0vvr9vwgvj3h3fr02taeq5xx64s0p4uvsra9vstqrqseqv3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bTRsd1hhTEUyVis1Q3FF
            ZmJUc3NvRnAxQ3lKQXlZWGZnK0xVc3Y1VUdjClJsUlJLeE9OSWxiSHliTHBML0hr
            Vnd5NWk1YW5hNWR2U2U3c2hVelh2eTQKLS0tIDhvdkVQakZrdFp4UVhVbVBCeEEx
            djNVNnB5aG1WU1BlTkl6TlNaSngyaVEKGWsY27QuFU1U8tLgse4EOB+j3GDYlRhv
            OIgcgx0fRTh7GI1/LNjFX3k8OIT1TLZWzhwtO/Rj7ri72QoqHEqpPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T14:56:15Z"
    mac: ENC[AES256_GCM,data:rgaJ7fQatMu0BSeJiPQk6xT+5rwzUIJFc0yPQesGBFmPTN/ImbuFsVMRd66A3ERJMy6q09rAoTgWB0ELaGy9LucglqCkZF28UtU5s6uJ39n/wiU4De8UCLUfCG8ZgZl97pzdKpKPH6De8LMX2MJt012dwmEe0Dcz/5ZdSUZ76mk=,iv:5raiB5duV2L1bgTvUj+1TFJWdouBHNKEZx3aRW4kSSY=,tag:bNcZJvVuI/GGisZaf39Ezw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
