config:
    notifications:
        slack.yaml: ENC[AES256_GCM,data:WZ3n1HM9qlQ+Eljnk4FjFTzTXVHpE8ho6hSLaJUEUo/ihFzHOtaL+cRBJ3rox1HczsKrPczZsKdHX7a4yVfO/U2LWcWuiCC+8C1s5pyh3AHq2SmeHWKzi4NvRyO5ZtgM6FTE9pnPEdEA7upw0MOIX1jg9JxO2CcWi8hJBpYfJtqMpR92uKqSH5UziWxS4kWm3qKlxxCVAJbjotRhqMQhIirxs0p3bSnwwbvlaecyRFQBYDQDk+JMnxeidtPHZsZzfpIRd/RHQZVd/sD6nX36ckxrYcdhGUWsldvL3TLs9py0V2hJd/KOiY3KkmppqQX7zKLp0ExM8H6NBjg+ko4bo8XSF2xA5BJ3Su1+ayQHmrtQCwJVPK1Bvj9QKitylzKLcxDQ7Wk6mY5P9z7D4FNXJRquOMuJE7DjoX6YMBEXtdfm4uMMze3qexzZ8qgkbe1MZEjGNrnJXvR7plVOFMBgBrimsFuES3IAXV9NutCJL1wRJrl/PNIZEQM9QxdtR3C4hGyA/hlnvqhqbuL9/Ur8ikxF7iMv7MiHD4VrkDwmqeCNdwxN5Gt/tHo6tQhj/Tq19Z02GeXVgdamhNRMdKNWmwg/n3tP6yr5pcPN3KDGDk615odLJVfewlX5k987sHJEPPfeeaHlIDV/gUoiSHh82Oq+1dgK1kNALhiOjXHGteb/4F6/tj1coJ0nTEejceGYPifkXvqtN6TSxK/GFceSeRjRIjFIzZ+wp4C5F3gtyYw8ztJhNSQOFKWDKDjH4cXP/SP9+l+lc3MtBcBawxcGCp4gfqZqfV3JuKIs9L289n+kXIv9hCu3OzghxSIH8mulg6qXbKTl3nMw3oZU6MCi7LWJutCf1rMZPR7lfwDJkEDGDHEZ75/8q44T43u+o0CChTPYu0O/Cd7/aOY73rKVdB2TnaGPOJJMbPODKi1Hpz4CdF+dPCOwzlMTieGdvOZAjb/JAu4FUXQtc6yYGFn+lf5mLYKhZsW8IZCZQ5A+2d38c9yPI5kdTC9Gq3oBf5BeFoIRAqcs2p9qi1Sfgx4=,iv:Csv9j+V3aKEtcsSF79+1x0dj/294D4WRfOrqmchnHKk=,tag:AotQhxnd456lKH48ip5f+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12th6l9858s0vvr9vwgvj3h3fr02taeq5xx64s0p4uvsra9vstqrqseqv3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeFVOOGZ1elV6dllzbk13
            OGZqTXNaQmRPV0M5TkhMdWR6YW94bmlzcVVvCklRWmxNYXQ1QzYrQ1B1QUg3SlJq
            NS9uQnppWEUyT044dHFSQmNvZHd2VlUKLS0tIGQ4d21LbitrUG1GMVRtdnl5K2dH
            RC83ZHpxNi9UYVhNaStJd3ZYTjJKLzgKLehXwwoWevMaEidIANafZUNjCCG/9dhW
            uc7qGiw9i2ot4Y3+GX4YMcOC8kAeEjnSZNBJ5zYVizdp8T96akKIsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T14:45:38Z"
    mac: ENC[AES256_GCM,data:fH1K+TgvIwFa8et4VZaUEaxoKyn7hbYKzTG8P0S46hwKj3hUl/2fxBzukQbs8mxQ7YmPXX5Y63pLhEZdS4e9XiD1ofkUUg7l/+NensABHOmkpqRBs1PuaJmesPkRoT/7IgQRBHkjXThwX0w+2p893AwLsBkM3zopKfR+oMKGhTc=,iv:71VZaJe/X2y9tkc0yTKKO/ddz0axz7ijs3kJiMvNCQQ=,tag:pk1RdosliOecwSvk8lYoSw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
